import Head from 'next/head'
import Hero from "../components/Hero";
import NavBar from "../components/NavBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex md:justify-center min-h-min min-h-full p-10 md:p-20 duration-300">
          <div className="w-2/5">
              <Hero heading="Blog" />
              <NavBar page='blog'/>
          </div>
      </div>
    </>
  )
}
