import Head from 'next/head'
import Hero from "../components/Hero";
import BlogList from "../components/BlogList";
import {articles} from "../components/ArticleData";

export default function Home() {
    return (
        <>
            <Head>
                <title>Blog</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <div className="px-8 md:px-24 ease-in duration-300">
                    <Hero/>
                    <BlogList articles={articles}/>
                </div>
            </div>
        </>
    )
}
